### ISSUE TITLE
Hi,  why does it work like this? How can i fix this?

### ISSUE THREAD

**Issue by sevostei** [AnLoMinus/Diablo#2]
./Diablo: 18: .: cannot open ../HacKingPro/HacKingPro-Parts/Main/HacKingPro-Planning: No such file

![Снимок экрана (2)](https://user-images.githubusercontent.com/93797500/198852509-6f2c76df-a7a6-40b0-b985-b3d74fdfc294.png)

**Comment by AnLoMinus** [comment]
**Hi**

How you run it?

you need run it or like that 
- `./Doablo`
- `sh Diablo`
- `zsh Diablo`

https://user-images.githubusercontent.com/51442719/198862048-efc08b55-0908-4600-bf89-0bda61720b6a.mp4

**Comment by sevostei** [comment]
I repeated with the video, the same error comes out
![Снимок экрана (3)](https://user-images.githubusercontent.com/93797500/198869477-588ee0d3-7a86-4ab2-a81f-6ece9a33898b.png)

Diablo: 18: .: cannot open ../HacKingPro/HacKingPro-Parts/Main/HacKingPro-Planning: No such file

**Comment by AnLoMinus** [comment]
Run please this command:
```cmd
cat /etc/shells
```
My OutPut:
```cmd
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
```

show your version of used shell
```cmd
sh --version
```

and Environment Variables;
```cmd
env
```

**Comment by AnLoMinus** [comment]
i working on new tool which is upgraded version of this tool:
 
## ⫷ [**`HacKingPro`**](https://github.com/Anlominus/HacKingPro) ⫸

**Comment by sevostei** [comment]
Your new application was able to run, apparently the problem is in the system on which I work, thanks for the help!
